CRITICAL - 2021-06-02 19:32:37 --> syntax error, unexpected '}', expecting end of file
#0 C:\xampp\htdocs\msbd\system\Router\Router.php(170): CodeIgniter\Router\Router->autoRoute('account/login')
#1 C:\xampp\htdocs\msbd\system\CodeIgniter.php(816): CodeIgniter\Router\Router->handle('account/login')
#2 C:\xampp\htdocs\msbd\system\CodeIgniter.php(385): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\xampp\htdocs\msbd\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\msbd\public\index.php(44): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\msbd\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2021-06-02 19:35:09 --> Undefined property: App\Controllers\Account::$input
#0 C:\xampp\htdocs\msbd\app\Controllers\Account.php(19): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 19, Array)
#1 C:\xampp\htdocs\msbd\system\CodeIgniter.php(936): App\Controllers\Account->proses_login()
#2 C:\xampp\htdocs\msbd\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
#3 C:\xampp\htdocs\msbd\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\msbd\public\index.php(44): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\msbd\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2021-06-02 19:37:15 --> Undefined property: App\Controllers\Account::$input
#0 C:\xampp\htdocs\msbd\app\Controllers\Account.php(19): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 19, Array)
#1 C:\xampp\htdocs\msbd\system\CodeIgniter.php(936): App\Controllers\Account->proses_login()
#2 C:\xampp\htdocs\msbd\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
#3 C:\xampp\htdocs\msbd\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\msbd\public\index.php(44): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\msbd\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2021-06-02 19:37:50 --> Undefined property: App\Controllers\Account::$input
#0 C:\xampp\htdocs\msbd\app\Controllers\Account.php(20): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 20, Array)
#1 C:\xampp\htdocs\msbd\system\CodeIgniter.php(936): App\Controllers\Account->proses_login()
#2 C:\xampp\htdocs\msbd\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
#3 C:\xampp\htdocs\msbd\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\msbd\public\index.php(44): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\msbd\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2021-06-02 19:38:05 --> Undefined property: App\Controllers\Account::$load
#0 C:\xampp\htdocs\msbd\app\Controllers\Account.php(22): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 22, Array)
#1 C:\xampp\htdocs\msbd\system\CodeIgniter.php(936): App\Controllers\Account->proses_login()
#2 C:\xampp\htdocs\msbd\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
#3 C:\xampp\htdocs\msbd\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\msbd\public\index.php(44): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\msbd\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2021-06-02 19:39:18 --> Class 'App\Controllers\LoginModel' not found
#0 C:\xampp\htdocs\msbd\system\CodeIgniter.php(936): App\Controllers\Account->proses_login()
#1 C:\xampp\htdocs\msbd\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
#2 C:\xampp\htdocs\msbd\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\msbd\public\index.php(44): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\msbd\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2021-06-02 19:39:46 --> Class 'CI_Model' not found
#0 C:\xampp\htdocs\msbd\system\Autoloader\Autoloader.php(294): include_once()
#1 C:\xampp\htdocs\msbd\system\Autoloader\Autoloader.php(265): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\msbd\system\Autoloader\Autoloader.php(228): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Logi...')
#3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Logi...')
#4 C:\xampp\htdocs\msbd\app\Controllers\Account.php(20): spl_autoload_call('App\\Models\\Logi...')
#5 C:\xampp\htdocs\msbd\system\CodeIgniter.php(936): App\Controllers\Account->proses_login()
#6 C:\xampp\htdocs\msbd\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
#7 C:\xampp\htdocs\msbd\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\msbd\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\msbd\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2021-06-02 19:40:19 --> Class 'Model' not found
#0 C:\xampp\htdocs\msbd\system\Autoloader\Autoloader.php(294): include_once()
#1 C:\xampp\htdocs\msbd\system\Autoloader\Autoloader.php(265): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\msbd\system\Autoloader\Autoloader.php(228): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Logi...')
#3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Logi...')
#4 C:\xampp\htdocs\msbd\app\Controllers\Account.php(20): spl_autoload_call('App\\Models\\Logi...')
#5 C:\xampp\htdocs\msbd\system\CodeIgniter.php(936): App\Controllers\Account->proses_login()
#6 C:\xampp\htdocs\msbd\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
#7 C:\xampp\htdocs\msbd\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\msbd\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\msbd\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2021-06-02 19:40:37 --> Undefined property: App\Controllers\Account::$LoginModel
#0 C:\xampp\htdocs\msbd\app\Controllers\Account.php(25): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 25, Array)
#1 C:\xampp\htdocs\msbd\system\CodeIgniter.php(936): App\Controllers\Account->proses_login()
#2 C:\xampp\htdocs\msbd\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
#3 C:\xampp\htdocs\msbd\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\msbd\public\index.php(44): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\msbd\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2021-06-02 19:42:10 --> Undefined property: App\Controllers\Account::$model
#0 C:\xampp\htdocs\msbd\app\Controllers\Account.php(25): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 25, Array)
#1 C:\xampp\htdocs\msbd\system\CodeIgniter.php(936): App\Controllers\Account->proses_login()
#2 C:\xampp\htdocs\msbd\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
#3 C:\xampp\htdocs\msbd\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\msbd\public\index.php(44): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\msbd\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2021-06-02 19:42:43 --> Undefined variable: username
#0 C:\xampp\htdocs\msbd\app\Controllers\Account.php(25): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 25, Array)
#1 C:\xampp\htdocs\msbd\system\CodeIgniter.php(936): App\Controllers\Account->proses_login()
#2 C:\xampp\htdocs\msbd\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
#3 C:\xampp\htdocs\msbd\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\msbd\public\index.php(44): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\msbd\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2021-06-02 19:43:40 --> You must set the database table to be used with your query.
#0 C:\xampp\htdocs\msbd\system\Model.php(615): CodeIgniter\Database\BaseConnection->table(NULL)
#1 C:\xampp\htdocs\msbd\system\Model.php(834): CodeIgniter\Model->builder()
#2 C:\xampp\htdocs\msbd\app\Controllers\Account.php(24): CodeIgniter\Model->__call('where', Array)
#3 C:\xampp\htdocs\msbd\system\CodeIgniter.php(936): App\Controllers\Account->proses_login()
#4 C:\xampp\htdocs\msbd\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
#5 C:\xampp\htdocs\msbd\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\msbd\public\index.php(44): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\msbd\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2021-06-02 19:44:31 --> syntax error, unexpected 'protected' (T_PROTECTED)
#0 C:\xampp\htdocs\msbd\system\Autoloader\Autoloader.php(265): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\msbd\system\Autoloader\Autoloader.php(228): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Logi...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Logi...')
#3 C:\xampp\htdocs\msbd\app\Controllers\Account.php(20): spl_autoload_call('App\\Models\\Logi...')
#4 C:\xampp\htdocs\msbd\system\CodeIgniter.php(936): App\Controllers\Account->proses_login()
#5 C:\xampp\htdocs\msbd\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
#6 C:\xampp\htdocs\msbd\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\msbd\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\msbd\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2021-06-02 19:45:00 --> You must set the database table to be used with your query.
#0 C:\xampp\htdocs\msbd\system\Model.php(615): CodeIgniter\Database\BaseConnection->table(NULL)
#1 C:\xampp\htdocs\msbd\system\Model.php(834): CodeIgniter\Model->builder()
#2 C:\xampp\htdocs\msbd\app\Controllers\Account.php(24): CodeIgniter\Model->__call('where', Array)
#3 C:\xampp\htdocs\msbd\system\CodeIgniter.php(936): App\Controllers\Account->proses_login()
#4 C:\xampp\htdocs\msbd\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
#5 C:\xampp\htdocs\msbd\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\msbd\public\index.php(44): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\msbd\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2021-06-02 19:47:34 --> syntax error, unexpected '}', expecting ';'
#0 C:\xampp\htdocs\msbd\system\Autoloader\Autoloader.php(265): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\msbd\system\Autoloader\Autoloader.php(228): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Logi...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Logi...')
#3 C:\xampp\htdocs\msbd\app\Controllers\Account.php(20): spl_autoload_call('App\\Models\\Logi...')
#4 C:\xampp\htdocs\msbd\system\CodeIgniter.php(936): App\Controllers\Account->proses_login()
#5 C:\xampp\htdocs\msbd\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
#6 C:\xampp\htdocs\msbd\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\msbd\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\msbd\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2021-06-02 19:47:46 --> You must set the database table to be used with your query.
#0 C:\xampp\htdocs\msbd\system\Model.php(615): CodeIgniter\Database\BaseConnection->table(NULL)
#1 C:\xampp\htdocs\msbd\system\Model.php(834): CodeIgniter\Model->builder()
#2 C:\xampp\htdocs\msbd\app\Controllers\Account.php(24): CodeIgniter\Model->__call('where', Array)
#3 C:\xampp\htdocs\msbd\system\CodeIgniter.php(936): App\Controllers\Account->proses_login()
#4 C:\xampp\htdocs\msbd\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
#5 C:\xampp\htdocs\msbd\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\msbd\public\index.php(44): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\msbd\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2021-06-02 19:50:50 --> syntax error, unexpected 'protected' (T_PROTECTED)
#0 C:\xampp\htdocs\msbd\system\Autoloader\Autoloader.php(265): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\msbd\system\Autoloader\Autoloader.php(228): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Logi...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Logi...')
#3 C:\xampp\htdocs\msbd\app\Controllers\Account.php(20): spl_autoload_call('App\\Models\\Logi...')
#4 C:\xampp\htdocs\msbd\system\CodeIgniter.php(936): App\Controllers\Account->proses_login()
#5 C:\xampp\htdocs\msbd\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
#6 C:\xampp\htdocs\msbd\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\msbd\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\msbd\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2021-06-02 19:52:02 --> Undefined property: App\Controllers\Account::$model
#0 C:\xampp\htdocs\msbd\app\Controllers\Account.php(24): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 24, Array)
#1 C:\xampp\htdocs\msbd\system\CodeIgniter.php(936): App\Controllers\Account->proses_login()
#2 C:\xampp\htdocs\msbd\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
#3 C:\xampp\htdocs\msbd\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\msbd\public\index.php(44): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\msbd\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2021-06-02 19:52:24 --> Undefined property: App\Controllers\Account::$LoginModel
#0 C:\xampp\htdocs\msbd\app\Controllers\Account.php(24): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 24, Array)
#1 C:\xampp\htdocs\msbd\system\CodeIgniter.php(936): App\Controllers\Account->proses_login()
#2 C:\xampp\htdocs\msbd\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
#3 C:\xampp\htdocs\msbd\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\msbd\public\index.php(44): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\msbd\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2021-06-02 19:53:43 --> Undefined property: App\Controllers\Account::$LoginModel
#0 C:\xampp\htdocs\msbd\app\Controllers\Account.php(24): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 24, Array)
#1 C:\xampp\htdocs\msbd\system\CodeIgniter.php(936): App\Controllers\Account->proses_login()
#2 C:\xampp\htdocs\msbd\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
#3 C:\xampp\htdocs\msbd\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\msbd\public\index.php(44): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\msbd\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2021-06-02 19:56:51 --> Class 'App\Controllers\UserModel' not found
#0 C:\xampp\htdocs\msbd\system\CodeIgniter.php(936): App\Controllers\Account->proses_login()
#1 C:\xampp\htdocs\msbd\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
#2 C:\xampp\htdocs\msbd\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\msbd\public\index.php(44): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\msbd\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2021-06-02 20:01:09 --> Cannot use object of type App\Models\LoginModel as array
#0 C:\xampp\htdocs\msbd\system\CodeIgniter.php(936): App\Controllers\Account->proses_login()
#1 C:\xampp\htdocs\msbd\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
#2 C:\xampp\htdocs\msbd\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\msbd\public\index.php(44): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\msbd\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2021-06-02 20:01:29 --> Cannot use object of type App\Models\LoginModel as array
#0 C:\xampp\htdocs\msbd\system\CodeIgniter.php(936): App\Controllers\Account->proses_login()
#1 C:\xampp\htdocs\msbd\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Account))
#2 C:\xampp\htdocs\msbd\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\msbd\public\index.php(44): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\msbd\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2021-06-02 20:05:15 --> syntax error, unexpected '}', expecting end of file
#0 C:\xampp\htdocs\msbd\system\Router\Router.php(170): CodeIgniter\Router\Router->autoRoute('account/proses_...')
#1 C:\xampp\htdocs\msbd\system\CodeIgniter.php(816): CodeIgniter\Router\Router->handle('account/proses_...')
#2 C:\xampp\htdocs\msbd\system\CodeIgniter.php(385): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\xampp\htdocs\msbd\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\msbd\public\index.php(44): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\msbd\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#6 {main}
ERROR - 2021-06-02 20:49:41 --> mysqli_sql_exception: Table 'kelurahan.users' doesn't exist in C:\xampp\htdocs\msbd\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\msbd\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT *\nFROM `...')
#1 C:\xampp\htdocs\msbd\system\Database\BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\msbd\system\Database\BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\msbd\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\msbd\system\Model.php(247): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\msbd\system\BaseModel.php(624): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\msbd\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(156): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\msbd\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(20): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#8 C:\xampp\htdocs\msbd\vendor\myth\auth\src\Controllers\AuthController.php(85): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#9 C:\xampp\htdocs\msbd\system\CodeIgniter.php(936): Myth\Auth\Controllers\AuthController->attemptLogin()
#10 C:\xampp\htdocs\msbd\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#11 C:\xampp\htdocs\msbd\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\msbd\public\index.php(44): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\msbd\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2021-06-02 20:49:41 --> Table 'kelurahan.users' doesn't exist
#0 C:\xampp\htdocs\msbd\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT *\nFROM `...')
#1 C:\xampp\htdocs\msbd\system\Database\BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\msbd\system\Database\BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\msbd\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\msbd\system\Model.php(247): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\msbd\system\BaseModel.php(624): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\msbd\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(156): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\msbd\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(20): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#8 C:\xampp\htdocs\msbd\vendor\myth\auth\src\Controllers\AuthController.php(85): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#9 C:\xampp\htdocs\msbd\system\CodeIgniter.php(936): Myth\Auth\Controllers\AuthController->attemptLogin()
#10 C:\xampp\htdocs\msbd\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#11 C:\xampp\htdocs\msbd\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\msbd\public\index.php(44): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\msbd\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#14 {main}
ERROR - 2021-06-02 20:51:39 --> mysqli_sql_exception: Table 'kelurahan.users' doesn't exist in C:\xampp\htdocs\msbd\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\msbd\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT 1\nFROM `...')
#1 C:\xampp\htdocs\msbd\system\Database\BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\msbd\system\Database\BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\msbd\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\msbd\system\Validation\Rules.php(212): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\msbd\system\Validation\Validation.php(306): CodeIgniter\Validation\Rules->is_unique('syifa', 'username', Array, NULL)
#6 C:\xampp\htdocs\msbd\system\Validation\Validation.php(164): CodeIgniter\Validation\Validation->processRules('username', 'username', 'syifa', Array, Array)
#7 C:\xampp\htdocs\msbd\system\Controller.php(181): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\msbd\vendor\myth\auth\src\Controllers\AuthController.php(161): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\msbd\system\CodeIgniter.php(936): Myth\Auth\Controllers\AuthController->attemptRegister()
#10 C:\xampp\htdocs\msbd\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#11 C:\xampp\htdocs\msbd\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\msbd\public\index.php(44): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\msbd\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2021-06-02 20:51:39 --> Table 'kelurahan.users' doesn't exist
#0 C:\xampp\htdocs\msbd\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT 1\nFROM `...')
#1 C:\xampp\htdocs\msbd\system\Database\BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\msbd\system\Database\BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\msbd\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\msbd\system\Validation\Rules.php(212): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\msbd\system\Validation\Validation.php(306): CodeIgniter\Validation\Rules->is_unique('syifa', 'username', Array, NULL)
#6 C:\xampp\htdocs\msbd\system\Validation\Validation.php(164): CodeIgniter\Validation\Validation->processRules('username', 'username', 'syifa', Array, Array)
#7 C:\xampp\htdocs\msbd\system\Controller.php(181): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\msbd\vendor\myth\auth\src\Controllers\AuthController.php(161): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\msbd\system\CodeIgniter.php(936): Myth\Auth\Controllers\AuthController->attemptRegister()
#10 C:\xampp\htdocs\msbd\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#11 C:\xampp\htdocs\msbd\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\msbd\public\index.php(44): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\msbd\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#14 {main}
ERROR - 2021-06-02 21:02:41 --> Email: sendWithMail throwed mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()
ERROR - 2021-06-02 21:02:42 --> Failed to send activation messaage to: syifaaulia311@gmail.com
ERROR - 2021-06-02 21:16:35 --> Email: sendWithSmtp throwed fsockopen(): SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
ERROR - 2021-06-02 21:16:35 --> Failed to send activation messaage to: syifaaulia311@gmail.com
ERROR - 2021-06-02 21:20:05 --> Email: sendWithSmtp throwed fsockopen(): SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
ERROR - 2021-06-02 21:20:05 --> Failed to send activation messaage to: syifaaulia311@gmail.com
ERROR - 2021-06-02 21:20:53 --> Email: sendWithSmtp throwed fsockopen(): SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
ERROR - 2021-06-02 21:20:53 --> Failed to send activation messaage to: syifaaulia311@gmail.com
ERROR - 2021-06-02 21:23:57 --> Email: sendWithSmtp throwed fsockopen(): SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
ERROR - 2021-06-02 21:23:57 --> Failed to send activation messaage to: dinimustika1216@gmail.com
CRITICAL - 2021-06-02 21:44:40 --> View themes, no current section.
#0 C:\xampp\htdocs\msbd\vendor\myth\auth\src\Views\login.php(113): CodeIgniter\View\View->endSection()
#1 C:\xampp\htdocs\msbd\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\msbd\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\msbd\system\Common.php(1217): CodeIgniter\View\View->render('Myth\\Auth\\Views...', Array, true)
#4 C:\xampp\htdocs\msbd\vendor\myth\auth\src\Controllers\AuthController.php(54): view('Myth\\Auth\\Views...', Array)
#5 C:\xampp\htdocs\msbd\system\CodeIgniter.php(936): Myth\Auth\Controllers\AuthController->login()
#6 C:\xampp\htdocs\msbd\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#7 C:\xampp\htdocs\msbd\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\msbd\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\msbd\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#10 {main}
